### ISSUE TITLE
Unable to Load podman on mxlinux

### ISSUE THREAD

**Issue by byteshiva** [flathub/io.podman_desktop.PodmanDesktop#15]
I'm having trouble running Podman on MX Linux. It seems to be failing, and I'm not sure if there's something I'm missing

```
uname -a 
Linux mx-cloud 6.0.0-6mx-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~mx21+1 (2022-12-15) x86_64 GNU/Linux
```

```
 flatpak run io.podman_desktop.PodmanDesktop -v
[3:0317/205712.061914:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Gtk-Message: 20:57:12.578: Failed to load module "canberra-gtk-module"
[3:0317/205712.618563:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0317/205712.618602:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[42:0317/205712.650098:ERROR:gpu_memory_buffer_support_x11.cc(49)] dri3 extension not supported.
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:0317/205712.683409:ERROR:bus.cc(562)] Failed to get the ownership of org.kde.StatusNotifierItem-3-1: org.freedesktop.DBus.Error.ServiceUnknown
Activating extension (crc)
[crc] Can not find CRC binary!
Activation extension (crc) ended
Activating extension (docker)
Activation extension (docker) ended
Activating extension (kube-context)
[kube-context] starting extension kube-context
Activation extension (kube-context) ended
Activating extension (lima)
[lima] Could not find podman socket at /home/siva/.lima/podman-lima/sock/podman.sock nor /home/siva/.lima/podman-lima/sock/podman.sock
Activation extension (lima) ended
Activating extension (podman)
Activating extension (registries)
Activation extension (registries) ended
[podman] Error while pinging docker as podman Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
(node:3) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, watch '/var/run/docker.sock'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at createFsWatchInstance (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(Use `podman-desktop --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
PluginSystem: received dom-ready event from the UI
[podman] Podman extension: Could not find the socket at /run/user/1000/podman/podman.sock after 5s. The command podman system service --time=0 did not work to start the podman socket.
Activation extension (podman) ended
PluginSystem: initialization done.
Delayed startup, flushing 9 events
Autostarting container engine
```

**Comment by benoitf** [comment]
it should be fixed with 0.13.0

**Comment by byteshiva** [comment]
I'm getting this error 

![image](https://user-images.githubusercontent.com/10637299/229109496-2b5dc7fb-d703-463f-8b2c-f195d1a158ad.png)

**Comment by benoitf** [comment]
It works. You have a warning saying that/var/run/docker.sock is not managed by podman so if you have tools using this socket it won't work but it may not be an issue
